@startuml architecture

title: High-level architecture

' actor :User: as user

node "IoT sensor" as esp {
    [WiFi packet sensor] as wifi
}

node "Fog server" as rpi {
    [Backend & APIs] as restPi
    [PubSub broker] as mqtt
    [WebUI] as angularPi
}

wifi --> mqtt
mqtt --> restPi
angularPi --> restPi

cloud "Cloud backend" as gcp {
    [Backend & APIs] as restCloud
    [WebUI] as angularCloud

    database "Cloud DB" as db {
        [resources] as resources
    }
}

restPi --> restCloud
restCloud --> resources
angularCloud --> restCloud

' actor :User: as user
' user -left-> angularPi
' user -left-> angularCloud

@enduml
