@startuml use-case

title: Use cases of a WiFi crowd sensor system

' actor :User: as user

actor :Student: as student
actor :Staff: as staff

' user <|-- student
' user <|-- staff

rectangle "System interface" as ui {
    (show number of people) as counter
    (show non sensitive stats) as stats
    (get info on popular device manufacturer) as vendor
    (get most crowded hours) as history

    stats --> vendor
    stats --> history

    counter -[hidden]down- stats

    student -right-> counter
    staff -right-> counter
    staff -right-> stats

    note "This data should be\naccessible easily\n(unauthenticated)" as n
    n -[hidden]left- counter
    n -[hidden]left- stats
}

@enduml
